nonzero_exit_errors = true

startup = [
  "mkdir ~/.cache/starship",
  "starship init nu | save ~/.cache/starship/init.nu",
  "source ~/.cache/starship/init.nu",
  "source ~/.config/nu/aliases.nu",
  "source ~/.config/nu/liz.nu",
]

prompt = "starship_prompt"